name: mynote
description: "Note App"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # B
  better_player: ^0.0.84

  # C
  cupertino_icons: ^1.0.6
  cloudinary_public: ^0.23.1
  chewie: ^1.8.1

  # D
  dio: ^5.4.1
  dart_jsonwebtoken: ^2.13.0
  vsc_quill_delta_to_html: ^1.0.5

  # I
  image_picker: ^1.1.2

  # S
  sqflite: ^2.3.2

  # F
  flutter_local_notifications: ^17.2.1+1
  flutter_secure_storage: ^9.0.0
  flutter_timezone: ^1.0.8
  file_picker: ^8.0.6
  flutter_image_compress: ^2.3.0
  flutter_quill_delta_from_html: ^1.1.5
  flutter_quill: ^9.5.14
  flutter_spinkit: ^5.2.1
  flutter_widget_from_html: ^0.15.1

  # P
  provider: ^6.1.2
  permission_handler: ^11.3.1

  # T
  timezone: ^0.9.4

  # V
  video_player: ^2.9.1
  video_compress_v2: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true